project:
  type: website
  execute-dir: file
  output-dir: "_site/"
  resources: 
    - "*.pdf"
   
lang: es
date-format: "[Xalapa, Ver.,] D [de] MMMM, YYYY"
fig-align: center

css: cicc.css

website:
  title: "CICC-R-Py"
  favicon: img/logo-cicc.png

  search: true

format:
  html:
    theme: Yeti 
    lightbox: true
    embed-resources: true
    
